# https://docs.docker.com/compose/compose-file/05-services/
services:

  app:
    entrypoint:
      - sleep
      - infinity
    image: node:20
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
