// Code generated by goctl. DO NOT EDIT.

import axios, { AxiosRequestConfig } from "axios"
import qs from "qs"
import * as components from "./chatroomComponents"
export * from "./chatroomComponents"

// https://axios-http.com/zh/docs/intro
export const http = axios.create();

/**
 * @description WS
 */
export function client_public_ws(config?: AxiosRequestConfig) {
  return http.get<null>(`client/public/ws`, config)
}

/**
 * @description 进入聊天室
 */
export function client_user_EnterRoom(id: number, config?: AxiosRequestConfig) {
  return http.get<components.Client_User_EnterRoom_Response>(`client/user/rooms/${id}`, config)
}
