// Code generated by goctl. DO NOT EDIT.

export interface Client_User_EnterRoom_Request {
}
export interface Client_User_EnterRoom_RequestParams {
}

export interface Client_User_EnterRoom_Response {
}

