// Code generated by goctl. DO NOT EDIT.

export interface Client_Public_GetSignUpCaptcha_Request {
}

export interface Client_Public_GetSignUpCaptcha_Response {
}

export interface Client_Public_CheckSignUpCaptcha_Request {
}

export interface Client_Public_CheckSignUpCaptcha_Response {
}

export interface Client_Public_SignUpAccount_Request {
  account: string // 账号
  password: string // 密码（前端加密后提交）
  captcha_code: string // 图形验证码
}

export interface Client_Public_SignUpAccount_Response {
  token: string
}

export interface Client_Public_SignUpMobile_Request {
  country_code: string // 国际区号
  mobile: string // 手机号码
  sms_code: string // 短信验证码
}

export interface Client_Public_SignUpMobile_Response {
  token: string
}

export interface Client_Public_SendSignUpSMS_Request {
  country_code: string // 国际区号
  mobile: string // 手机号码
  captcha_code: string // 图形验证码
}

export interface Client_Public_SendSignUpSMS_Response {
  exp_timestamp: string // 短信验证码有效期时间戳
  remaining_retries: string // 输入错误剩余重试次数
}

export interface Client_Public_GetSignInCaptcha_Request {
}

export interface Client_Public_GetSignInCaptcha_Response {
}

export interface Client_Public_CheckSignInCaptcha_Request {
}

export interface Client_Public_CheckSignInCaptcha_Response {
}

export interface Client_Public_SignInAccount_Request {
  account: string // 账号
  password: string // 密码（前端加密后提交）
  captcha_code: string // 图形验证码
}

export interface Client_Public_SignInAccount_Response {
  token: string
}

export interface Client_Public_SignInMobile_Request {
  country_code: string // 国际区号
  mobile: string // 手机号码
  sms_code: string // 短信验证码
}

export interface Client_Public_SignInMobile_Response {
  token: string
}

export interface Client_Public_SendSignInSMS_Request {
  country_code: string // 国际区号
  mobile: string // 手机号码
  captcha_code: string // 图形验证码
}

export interface Client_Public_SendSignInSMS_Response {
  exp_timestamp: string // 短信验证码有效期时间戳
  remaining_retries: string // 输入错误剩余重试次数
}

export interface Client_User_SignOut_Request {
}

export interface Client_User_SignOut_Response {
}

export interface Client_User_EditPassword_Request {
  original_password: string // 原始密码（前端加密后提交）
  new_password: string // 新的密码（前端加密后提交）
}

export interface Client_User_EditPassword_Response {
}

